---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

version: '3.7'

services:
  ostoslista-api:
    image: 'mireiawen/ostoslista-webhook'
    build:
      context: '.'
    restart: 'unless-stopped'
    networks:
    - 'traefik'
    environment:
      DISCORD_HOOK: '$DISCORD_HOOK'
    labels:
    - 'traefik.enable=true'
    - 'traefik.docker.network=traefik'
    - 'traefik.http.routers.ostoslista-api.rule=Host(`$HOSTNAME.$DOMAIN`)'
    - 'traefik.http.routers.ostoslista-api.entrypoints=websecure'
    - 'traefik.http.routers.ostoslista-api.middlewares=$MIDDLEWARE'
    - 'traefik.http.routers.ostoslista-api.service=ostoslista-api'
    - 'traefik.http.services.ostoslista-api.loadbalancer.passhostheader=true'

networks:
  traefik:
    external: true
