---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

version: '3.7'

services:
  ostoslista-api:
    image: 'mireiawen/ostoslista-webhook'
    build:
      context: '.'
    restart: 'always'
    network_mode: 'bridge'
    hostname: '$HOSTNAME.$DOMAIN'
    container_name: 'ostoslista-api'
    environment:
      DISCORD_HOOK: '$DISCORD_HOOK'
    labels:
    - 'traefik.enable=true'
    - 'traefik.http.routers.ostoslista-api.rule=Host(`$HOSTNAME.$DOMAIN`)'
    - 'traefik.http.routers.ostoslista-api.entrypoints=web'
    - 'traefik.http.routers.ostoslista-api.middlewares=ostoslista-api-whitelist,http-to-https'
    - 'traefik.http.routers.ostoslista-api.service=ostoslista-api'
    - 'traefik.http.routers.ostoslista-api-secure.rule=Host(`$HOSTNAME.$DOMAIN`)'
    - 'traefik.http.routers.ostoslista-api-secure.entrypoints=websecure'
    - 'traefik.routers.ostoslista-api-secure.middlewares=ostoslista-api-whitelist'
    - 'traefik.http.routers.ostoslista-api-secure.service=ostoslista-api'
    - 'traefik.http.middlewares.ostoslista-api-whitelist.ipwhitelist.sourcerange=$NETWORKS'
    - 'traefik.http.services.ostoslista-api.loadbalancer.passhostheader=true'
